services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=elysia
      - POSTGRES_USER=elysia
      - POSTGRES_PASSWORD=elysia
    volumes:
      - elysia_pgdata:/var/lib/postgresql/data

volumes:
  elysia_pgdata:
    name: elysia_pgdata